web:
  build: .
  container_name: todolist
  ports:
    - "5000:5000"
  volumes:
    - .:/todo

  links:
    - db

db:
  image: mongo:3.2.0
  restart: always
  ports:
    - "27017:27017"
  volumes:
    - ./db/data:/db/data
